"""
Lead enrichment — turn a username + company hint into a real LinkedIn profile.

When the people stream finds  `u/seoul_founder42` on Reddit or `네이버유저` on
Naver, we don't have a LinkedIn URL — and we can't DM them. This module bridges
that gap by searching LinkedIn (no cookies, no login) for a likely match using
HarvestAPI's name-search and full-profile actors.

Cost discipline:
  • only enrich top-N leads per cycle (caller's responsibility)
  • in-process LRU cache by (name_lower, company_lower) so the same lead isn't
    re-billed on every campaign cycle
  • optional email lookup ($10/1k) is opt-in via `with_email=True`
"""

from __future__ import annotations

import threading
from typing import Any

from agent.tools import _apify_run

# ─── In-process cache ─────────────────────────────────────────────────────


_CACHE: dict[tuple[str, str], dict] = {}
_CACHE_LOCK = threading.Lock()
_CACHE_MAX = 500


def _cache_key(name: str, company: str) -> tuple[str, str]:
    return ((name or "").strip().lower(), (company or "").strip().lower())


def _cache_get(name: str, company: str) -> dict | None:
    with _CACHE_LOCK:
        return _CACHE.get(_cache_key(name, company))


def _cache_put(name: str, company: str, value: dict) -> None:
    with _CACHE_LOCK:
        if len(_CACHE) >= _CACHE_MAX:
            # Cheap eviction: drop oldest insertion.
            try:
                _CACHE.pop(next(iter(_CACHE)))
            except StopIteration:
                pass
        _CACHE[_cache_key(name, company)] = value


# ─── Helpers ──────────────────────────────────────────────────────────────


_NOISE_NAMES = {
    "redditor", "anonymous", "anon", "user", "guest",
    "linkedin user", "blind user", "naver user", "weibo user",
    "rednote user", "qiita user", "zhihu user",
}


def looks_like_real_name(name: str | None) -> bool:
    """Cheap filter so we don't waste Apify on autogenerated handles."""
    if not name:
        return False
    n = name.strip()
    if len(n) < 3 or len(n) > 80:
        return False
    if n.lower() in _NOISE_NAMES:
        return False
    if n.startswith("u/") or n.startswith("/u/"):
        return False
    if any(c in n for c in "@/_<>"):
        return False
    # Two whitespace-separated tokens looks human; or a 2+ char CJK string.
    parts = n.split()
    if len(parts) >= 2 and all(len(p) >= 2 for p in parts[:2]):
        return True
    if any(0x3040 <= ord(c) <= 0x9FFF for c in n):  # CJK range
        return len(n) >= 2
    return False


def _split_name(name: str) -> tuple[str, str]:
    parts = name.strip().split()
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], " ".join(parts[1:])


def _company_to_linkedin_url(company: str) -> str:
    if not company:
        return ""
    slug = company.lower().strip()
    for ch in (" ", ".", ",", "/"):
        slug = slug.replace(ch, "-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return f"https://www.linkedin.com/company/{slug.strip('-')}"


# ─── Public API ───────────────────────────────────────────────────────────


def enrich_lead_via_linkedin(
    name: str,
    company_hint: str | None = None,
    locations: list[str] | None = None,
    with_email: bool = False,
    campaign_id: str | None = None,
) -> dict:
    """
    Look up `name` on LinkedIn (filtered by `company_hint` if given).

    Returns a dict with the enriched fields the caller can merge into the lead:

        {
          "linkedin_url": str,
          "headline":     str,
          "company":      str,
          "location":     str,
          "email":        str,        # only if with_email=True
          "match_score":  float,      # 0.0 – 1.0 confidence (rough)
        }

    On failure / no match, returns an empty-ish dict (still safe to .get()).
    """
    if not looks_like_real_name(name):
        return {}

    cached = _cache_get(name, company_hint or "")
    if cached is not None:
        return cached

    first, last = _split_name(name)
    run_input: dict[str, Any] = {
        "profileScraperMode": "Full + email search" if with_email else "Full",
        "firstName": first,
        "lastName": last,
        "strictSearch": True,
        "maxPages": 1,
    }
    if company_hint:
        run_input["currentCompanies"] = [_company_to_linkedin_url(company_hint)]
    if locations:
        run_input["locations"] = locations[:3]

    items = _apify_run(
        "harvestapi/linkedin-profile-search-by-name",
        run_input,
        campaign_id=campaign_id,
        stream="signals",
        max_items=5,
        timeout_secs=120,
    )

    best: dict | None = None
    for it in items:
        prof = it.get("profile") or it
        url = (
            prof.get("profileUrl")
            or prof.get("publicProfileUrl")
            or prof.get("url")
            or ""
        )
        if not url:
            continue
        full_name = (
            prof.get("fullName")
            or prof.get("name")
            or f"{prof.get('firstName','')} {prof.get('lastName','')}".strip()
        )
        score = 0.5
        if company_hint and (
            company_hint.lower()
            in (
                str(prof.get("company") or prof.get("currentCompany") or "")
                + " "
                + str(prof.get("headline") or "")
            ).lower()
        ):
            score += 0.3
        if full_name and full_name.lower() == name.lower():
            score += 0.2
        candidate = {
            "linkedin_url": url,
            "headline": prof.get("headline") or prof.get("position") or "",
            "company": prof.get("company") or prof.get("currentCompany") or "",
            "location": prof.get("location") or "",
            "email": prof.get("email") or prof.get("emailAddress") or "",
            "match_score": round(score, 2),
        }
        if best is None or candidate["match_score"] > best["match_score"]:
            best = candidate

    result = best or {}
    _cache_put(name, company_hint or "", result)
    return result


def fetch_full_profile(
    profile_url: str,
    with_email: bool = True,
    campaign_id: str | None = None,
) -> dict:
    """Direct profile fetch — used when we already have a LinkedIn URL but
    need richer detail (email, headline, current company)."""
    if not profile_url:
        return {}
    items = _apify_run(
        "harvestapi/linkedin-profile-scraper",
        {
            "profileScraperMode": (
                "Profile details + email search ($10 per 1k)"
                if with_email
                else "Profile details no email ($4 per 1k)"
            ),
            "queries": [profile_url],
        },
        campaign_id=campaign_id,
        stream="signals",
        max_items=1,
        timeout_secs=120,
    )
    if not items:
        return {}
    p = items[0]
    return {
        "linkedin_url": profile_url,
        "headline": p.get("headline") or p.get("position") or "",
        "company": p.get("company") or p.get("currentCompany") or "",
        "location": p.get("location") or "",
        "email": p.get("email") or p.get("emailAddress") or "",
        "full_name": p.get("fullName") or p.get("name") or "",
    }


__all__ = ["enrich_lead_via_linkedin", "fetch_full_profile", "looks_like_real_name"]
